name          'example42-collectd'
version '3.0.5'
author        'Alessandro Franceschi'
project_page  'http://www.example42.com'
source        'https://github.com/example42/puppet-collectd'
license       'Apache License, Version 2.0'
summary       'This module installs and manages collectd'
description   'This module installs and manages collectd. Based on stdmod/puppet-skeleton-standard 0.0.2.'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
